name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        check-latest: true

    - name: Check Go version
      run: go version

    - name: Clear Go build cache
      run: go clean -cache -modcache -i -r

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...
